"""Added devices table

Revision ID: 923eb25eef2c
Revises: 3fcf8ec61ee2
Create Date: 2022-11-30 15:52:06.734054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923eb25eef2c'
down_revision = '3fcf8ec61ee2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
