"""Add

Revision ID: f6d7796474e3
Revises: 6efb167b8fea
Create Date: 2022-11-30 15:49:50.032338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d7796474e3'
down_revision = '6efb167b8fea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
